"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gemini API Key
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'AIzaSyArGXMMHRnDxUkQgRFqGXMIbrIKDN3V2-E')

# Google OAuth Client ID
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '994681019100-121g9v8ps9ma6ir3cvioqsofq4s0ndip.apps.googleusercontent.com')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-p^!1!hqkymf9)#lgbyo$%1u0xlf5r-$$p&_p$plo(#&$($%!-u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['cemcedimoglu.me', 'www.cemcedimoglu.me', 'localhost', '127.0.0.1']

# ============== GÜVENLİK AYARLARI ==============
# HTTPS ayarları (production'da aktif)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Cloudflare/Nginx bunu hallediyor
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 yıl
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
# CSRF güvenilir kaynaklar
CSRF_TRUSTED_ORIGINS = [
    'https://cemcedimoglu.me',
    'https://www.cemcedimoglu.me',
]
# ===============================================


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'products',
    'corsheaders',
    'users.apps.UsersConfig',
    'rest_framework_simplejwt'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Docker ortamında PostgreSQL, yerel ortamda SQLite kullan
if os.environ.get('DATABASE_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME', 'eticaret_db'),
            'USER': os.environ.get('DATABASE_USER', 'eticaret_user'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'eticaret_secure_password_123'),
            'HOST': os.environ.get('DATABASE_HOST', 'db'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py dosyasının EN ALTINA ekle

# Yüklenen fotoğrafların URL'de nasıl görüneceği
# (Yani http://sunucu_ip/media/urun.jpg)
MEDIA_URL = '/media/'

# Yüklenen fotoğrafların sunucuda HANGİ KLASÖRE kaydedileceği
# BASE_DIR, projemizin ana klasörüdür (backend/)
# Biz de "backend/media_files" diye bir klasöre kaydet diyoruz.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_files')

# Yüklenen dosyaların izinleri (permission denied hatası için)
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

CORS_ALLOWED_ORIGINS = [
    'https://cemcedimoglu.me',
    'https://www.cemcedimoglu.me',
]
# Development ortamında tüm originlere izin ver
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

# 1. REST Framework'e varsayılan doğrulama (Authentication) yöntemini söylemek:
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Rate Limiting / Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',     # Anonim kullanıcılar: dakikada 100 istek
        'user': '300/minute',     # Giriş yapmış kullanıcılar: dakikada 300 istek
        'login': '5/minute',      # Login denemesi: dakikada 5
    }
}

# 2. JWT Ayarları (Token Ömrü vs.):
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # Token'ın geçerlilik süresi (1 saat yaptık)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),   # Yenileme Token'ının ömrü (1 gün)
    "ROTATE_REFRESH_TOKENS": True,                 # Her yenilemede yeni token ver
}

AUTH_USER_MODEL = 'users.CustomUser'