# Generated by Django 5.2.8 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İndirim Bitişi'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(default=0, verbose_name='İndirim Oranı (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İndirim Başlangıcı'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Yeni Ürün Etiketi'),
        ),
    ]
