# Generated by Django 5.2.8 on 2025-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_end_date_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='main_announcement_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ana Duyuru Metni'),
        ),
    ]
