# Generated by Django 5.2.8 on 2025-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_siteconfiguration_main_announcement_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='main_announcement_text',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='topbar_image',
            field=models.ImageField(blank=True, null=True, upload_to='topbar_banners/', verbose_name='Duyuru Görseli (1058x64px ideal)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='topbar_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Tıklanınca Gidilecek Link'),
        ),
    ]
