# Generated by Django 5.2.8 on 2025-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_category_parent_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Başlığı (Admin için)')),
                ('image', models.ImageField(upload_to='promo_banners/', verbose_name='Banner Görseli')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Tıklanınca Gidilecek Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama (Küçük önce)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklam Bannerı',
                'verbose_name_plural': 'Reklam Bannerları',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
