# Generated by Django 5.2.8 on 2025-11-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Bug Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('page_url', models.CharField(blank=True, max_length=500, null=True, verbose_name="Sayfa URL'i")),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='open', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Bildiren Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bug Bildirimi',
                'verbose_name_plural': 'Bug Bildirimleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
