# Generated by Django 5.2.8 on 2025-11-27 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu')),
                ('discount_percentage', models.IntegerField(verbose_name='İndirim Oranı (%)')),
                ('valid_from', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('valid_to', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('usage_limit', models.IntegerField(default=100, verbose_name='Kullanım Limiti')),
                ('used_count', models.IntegerField(default=0, verbose_name='Kullanım Sayısı')),
            ],
            options={
                'verbose_name': 'İndirim Kuponu',
                'verbose_name_plural': 'İndirim Kuponları',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon', verbose_name='Kullanılan Kupon'),
        ),
    ]
