# Generated by Django 5.2.8 on 2025-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum İndirim Tutarı'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Sepet Tutarı'),
        ),
    ]
