# Generated by Django 5.2.8 on 2025-11-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_coupon_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live_mode', models.BooleanField(default=False, help_text='Kapalı = Test Modu (Sahte ödemeler), Açık = Gerçek Ödemeler', verbose_name='Canlı Mod')),
                ('sandbox_api_key', models.CharField(blank=True, help_text='Iyzico Sandbox API anahtarı (Test için)', max_length=255, null=True, verbose_name='Sandbox API Key')),
                ('sandbox_secret_key', models.CharField(blank=True, help_text='Iyzico Sandbox gizli anahtarı (Test için)', max_length=255, null=True, verbose_name='Sandbox Secret Key')),
                ('live_api_key', models.CharField(blank=True, help_text='Iyzico Production API anahtarı', max_length=255, null=True, verbose_name='Canlı API Key')),
                ('live_secret_key', models.CharField(blank=True, help_text='Iyzico Production gizli anahtarı', max_length=255, null=True, verbose_name='Canlı Secret Key')),
                ('demo_mode', models.BooleanField(default=True, help_text='Açık = Gerçek API kullanılmaz, ödeme simüle edilir', verbose_name='Demo Modu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Ödeme Ayarları',
                'verbose_name_plural': 'Ödeme Ayarları',
            },
        ),
    ]
