# Generated by Django 5.2.8 on 2025-11-28 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_paymentsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=1, verbose_name='Görüntüleme Sayısı')),
                ('total_duration_seconds', models.IntegerField(default=0, verbose_name='Toplam Süre (saniye)')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Son Görüntüleme')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='İlk Görüntüleme')),
                ('added_to_cart', models.BooleanField(default=False, verbose_name='Sepete Eklendi mi?')),
                ('added_to_favorites', models.BooleanField(default=False, verbose_name='Favorilere Eklendi mi?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Davranışı',
                'verbose_name_plural': 'Kullanıcı Davranışları',
                'ordering': ['-total_duration_seconds', '-view_count'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
