# Generated by Django 5.2.8 on 2025-11-28 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_userbehavior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='session_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Oturum ID'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
