# Generated by Django 5.2.8 on 2025-12-02 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_userbehavior_session_id_alter_userbehavior_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parça Türü Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon (CSS class)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
            ],
            options={
                'verbose_name': 'Parça Türü',
                'verbose_name_plural': 'Parça Türleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Oturum ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yapılandırma Adı')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Fiyat')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'PC Yapılandırması',
                'verbose_name_plural': 'PC Yapılandırmaları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PCComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model_name', models.CharField(max_length=200, verbose_name='Model')),
                ('specifications', models.JSONField(default=dict, verbose_name='Teknik Özellikler')),
                ('compatibility_rules', models.JSONField(blank=True, default=dict, verbose_name='Uyumluluk Kuralları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.componenttype', verbose_name='Parça Türü')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc_component', to='products.product', verbose_name='Bağlı Ürün')),
            ],
            options={
                'verbose_name': 'PC Parçası',
                'verbose_name_plural': 'PC Parçaları',
                'ordering': ['component_type__order', 'brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='PCBuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_components', to='products.pcbuild')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_selections', to='products.pccomponent')),
            ],
            options={
                'verbose_name': 'Yapılandırma Parçası',
                'verbose_name_plural': 'Yapılandırma Parçaları',
                'unique_together': {('build', 'component')},
            },
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='components',
            field=models.ManyToManyField(related_name='builds', through='products.PCBuildComponent', to='products.pccomponent', verbose_name='Parçalar'),
        ),
    ]
