# Generated by Django 5.2.8 on 2025-12-01 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Evim, Okulum, İş Yerim', max_length=50, verbose_name='Adres Başlığı')),
                ('full_name', models.CharField(max_length=100, verbose_name='Alıcı Adı Soyadı')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle')),
                ('address_line', models.TextField(help_text='Sokak, bina no, daire no vb.', verbose_name='Açık Adres')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Adresi',
                'verbose_name_plural': 'Kullanıcı Adresleri',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
